font_family Hasklug Nerd Font
font_size 11

shell_integration no-rc

allow_cloning ask
background_blur 0
background_image_layout cscaled
background_image_linear yes
background_opacity 1
bold_font auto
bold_italic_font auto
color0 #444444
color1 #FFFFAA
color10 #FFDFDF
color11 #dbcdf2
color12 #e179e5
color13 #bc9ff9
color14 #7556ff
color15 #CCCCFF
color2 #FFAEAE
color3 #C7BBDC
color4 #B562B8
color5 #AA91E1
color6 #6348D5
color7 #AAAEEE
color8 #888888
color9 #ffffd8
cursor #FFAEAE
cursor_shape underline
cursor_stop_blinking_after 0
cursor_text_color #1F1E33
disable_ligatures never
dynamic_background_opacity yes
editor nvim
enable_audio_bell no
font_family Hasklug Nerd Font
font_features HasklugNF +calt
font_size 11
force_ltr no
hide_window_decorations yes
initial_window_height 768
initial_window_width 1366
italic_font auto
notify_on_cmd_finish unfocused
remember_window_size yes
selection_background #4C566A
selection_foreground #FFAEAE
shell .
shell_integration enabled
tab_bar_edge top
tab_bar_min_tabs 2
tab_bar_style separator
tab_separator \::\
tab_title_max_length 0
tab_title_template "{index} -> {title} "

