
misc {
        force_default_wallpaper = 1
        disable_hyprland_logo = true
        focus_on_activate = true
}

input {
        kb_layout = us
        kb_variant = dvorak
        kb_model =
        kb_options =
        kb_rules =

        follow_mouse = 1

        sensitivity = 0.3

        touchpad {
                natural_scroll = false
        }
}

gestures {
        gesture = 3, horizontal, workspace
}

plugin {
        hyprexpo {
                columns = 2
                gap_size = 4
                bg_col = rgb(1f1e33)
        }
}

device {
        name = veikk.inc-vk640-mouse
        output = eDP-1
}
