windowrule = suppressevent maximize, class:.*
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

windowrulev2 = noborder, fullscreen:1
windowrulev2 = noborder, class:^(kitty)$
windowrulev2 = rounding 0, class:^(kitty)$
windowrulev2 = noborder, class:^(dev.zed.Zed)$
windowrulev2 = rounding 0, class:^(dev.zed.Zed)$
windowrulev2 = noborder, class:^(xfreerdp)$
windowrulev2 = rounding 0, class:^(xfreerdp)$
windowrulev2 = rounding 2, floating:1
windowrulev2 = float, title:^(meow)$
windowrulev2 = float, class:^(feh)$
windowrulev2 = float, class:^(Free Download Manager)$
windowrulev2 = float, class:^(wev)$
# windowrulev2 = float, class:^(org.pwmt.zathura)$
windowrulev2 = size 50% 1077, class:^(org.pwmt.zathura)$
windowrulev2 = move 50% 2, class:^(org.pwmt.zathura)$
windowrulev2 = float, class:^(org.kde.dolphin)$
windowrulev2 = size 1366 768, class:^(org.kde.dolphin)$
windowrulev2 = size 50% 70%, class:^(org.qbittorrent.qBittorrent)$
windowrulev2 = float, class:^(org.qbittorrent.qBittorrent)$
windowrulev2 = size 320 180, title:^("Copying - Dolphin")$, class:^(org.kde.dolphin)$
windowrulev2 = float, title:(.*)Page(.*)
windowrulev2 = float, class:^(org.pulseaudio.pavucontrol)$
windowrulev2 = workspace 2, class:^(discord-stable)$
windowrulev2 = workspace 2, class:^(discord)$
windowrulev2 = workspace 2, class:^(zen)$
windowrulev2 = noborder, class:^(steam_app_312520)$
windowrulev2 = nofocus, class:^(Dunst)$
windowrulev2 = pin, class:^(Dunst)$
windowrulev2 = float, class:^(mpv)$, title:.*f4v.*
# windowrulev2 = noborder, class:(.*)youtube_music
windowrulev2 = opacity 0.85, class:(.*)youtube_music
windowrulev2 = float, class:^$

# pip rules
windowrulev2 = float, title:^(Picture-in-Picture)$
windowrulev2 = size 320 180, title:^(Picture-in-Picture)$
windowrulev2 = pin, title:^(Picture-in-Picture)$
windowrulev2 = content video, title:^(Picture-in-Picture)$
windowrulev2 = float, title:^(Discord Popout)$
windowrulev2 = content video, title:^(Discord Popout)$

# flameshot rules 
windowrulev2 = move 0 0, title:^(flameshot)$
windowrulev2 = pin, title:^(flameshot)$
windowrulev2 = fullscreenstate, title:^(flameshot)$
windowrulev2 = noanim, title:^(flameshot)$
windowrulev2 = float, title:^(flameshot)$

# android emulator rules
windowrulev2 = float   , class:^(Emulator)$
windowrulev2 = noborder, class:^(Emulator)$

# gimp rules 
windowrulev2 = size 460 270, title:^(Heal Selection)$
windowrulev2 = float, title:^(Heal Selection)$

# zen popup window rules
windowrule = float, title:^(Extension: \(Aria2 Download Manager Integration\) - Download Panel).*$, initialClass:^(zen-beta)$
windowrule = size 400 400, title:^(Extension: \(Aria2 Download Manager Integration\) - Download Panel).*$
